source 'https://rubygems.org'

gem 'rails', '5.1.4'
gem 'rake'

gem 'active_model_serializers'
gem 'acts-as-taggable-on'
gem 'addressable'
gem 'awesome_print'
gem 'bootstrap-sass'
gem 'bullet'
gem 'breadcrumbs_on_rails'
gem 'cancancan'
gem 'carrierwave'
gem 'config'
gem 'countries'
gem 'devise'
gem 'draper'
gem 'email_validator'
gem 'factory_bot_rails'
gem 'faker'
gem 'flutie'
gem 'font-awesome-rails'
gem 'friendly_id'
gem 'haml', '5.0'
gem 'haml-rails', '1.0'
gem 'has_scope'
gem 'kaminari'
gem 'launchy'
gem 'listen'
gem 'makara'
gem 'memoist'
gem 'meta-tags'
gem 'mini_racer', platforms: :ruby #v8
gem 'nokogiri'
gem 'paper_trail'
gem 'parallel'
gem 'pg'
gem 'puma'
gem 'rails_admin'
gem 'ransack'
gem 'sass-rails'
gem 'scientist'
gem 'shoryuken'
gem 'sitemap_generator'
gem 'state_machines'
gem 'state_machines-activerecord'
gem 'state_machines-audit_trail'
gem 'turbolinks'
gem 'uglifier'
gem 'whenever'

group :development, :test do
  gem 'byebug'
  gem 'spring'
end
