source 'https://rubygems.org'

gem 'rails', '5.2.2'
gem 'rake'

gem 'actionpack-action_caching'
gem 'active_model_serializers'
gem 'activejob'
gem 'acts-as-taggable-on'
gem 'acts_as_votable', '~> 0.11.1'
gem 'addressable'
gem 'awesome_print'
gem 'aws-sdk-sqs'
gem 'bootsnap', require: false
gem "bootstrap", ">= 4.3.1"
gem 'bullet'
# gem 'breadcrumbs_on_rails'
gem 'cancancan'
gem 'carrierwave'
gem 'config'
gem 'countries'
gem 'dalli'
gem 'devise'
gem 'draper'
gem 'elasticsearch', git: 'git://github.com/elasticsearch/elasticsearch-ruby.git'
gem 'faraday'
gem 'fast_jsonapi'
gem 'flutie'
gem 'font-awesome-sass'
gem 'friendly_id'
gem 'geocoder'
gem 'haml-rails'
gem 'has_scope'
# gem 'hiredis' # Highly recommended
gem 'i18n'
gem 'jquery-rails'
gem 'kaminari'
gem 'launchy'
gem 'listen'
gem 'makara'
gem 'memoist'
gem 'meta-tags'
gem 'mini_racer', platforms: :ruby #v8
gem 'money'
# gem 'mui-sass'
# gem 'nokogiri'
gem 'paper_trail'
gem 'parallel'
gem 'pg', '~> 0.20'
gem 'puma'
gem 'rails_admin'
gem 'ransack'
# gem 'sass-rails'
gem 'scientist'
gem 'slack-notifier'
gem 'shoryuken'
gem 'simple_form'
gem 'sitemap_generator'
gem 'state_machines'
gem 'state_machines-activerecord'
gem 'state_machines-audit_trail'
gem 'stripe'
gem 'turbolinks'
gem 'uglifier'
gem 'vueonrails'
gem 'webpacker', '~> 4.x'
gem 'whenever'

group :development, :test do
  gem 'binding_of_caller'
  gem 'byebug'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'letter_opener'
  gem 'spring'
end

group :development do
  gem 'annotate'
  gem 'rails_best_practices'
  gem 'better_errors'
  gem 'brakeman', require: false
  gem 'rails-erd', require: false
  gem 'web-console'
end

group :test do
  gem 'rails-controller-testing'
  gem 'rspec-collection_matchers'
  gem 'rspec-expectations'
  gem 'rspec-rails'
  gem 'rspec-rerun'
  gem 'simplecov', require: false
  gem 'timecop'
end
